const FETCH_FILES_REQUEST = 'FETCH_FILES_REQUEST'
const FETCH_FILES_SUCCESS = 'FETCH_FILES_SUCCESS'
const FETCH_FILES_FAILURE = 'FETCH_FILES_FAILURE'

module.exports = {
  FETCH_FILES_REQUEST,
  FETCH_FILES_SUCCESS,
  FETCH_FILES_FAILURE
}
